foreground #fefefe
background #000000

selection_foreground #fefefe
selection_background #2b2b2b

cursor #fefefe
cursor_text_color #000000

active_border_color #bdbdbd
active_tab_background #bdbdbd

# Normal colors
color0  #000000
color1  #fefefe
color2  #bdbdbd
color3  #cfcfcf
color4  #bdbdbd
color5  #bdbdbd
color6  #bdbdbd
color7  #fefefe

# Bright colors
color8  #1a1a1a
color9  #f5f5f5
color10 #bdbdbd
color11 #cfcfcf
color12 #bdbdbd
color13 #bdbdbd
color14 #bdbdbd
color15 #f5f5f5

# made by flyingaura
